# Generated by Django 2.2.1 on 2019-05-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190518_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenLog',
        ),
    ]
