# Generated by Django 2.2.1 on 2019-05-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190521_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='collection.Collection'),
        ),
    ]
