# Generated by Django 2.2.1 on 2019-05-18 06:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('language', models.IntegerField(choices=[(1, 'русский'), (2, 'қазақша'), (3, 'english')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utils.upload.avatar_upload)),
                ('avatar_big', models.ImageField(blank=True, null=True, upload_to=utils.upload.avatar_upload)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('review', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255, null=True), default=list, size=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_save', models.IntegerField(choices=[(30, 'on_save_30'), (31, 'on_save_31')], default=30)),
                ('on_full', models.IntegerField(choices=[(1, 'on_full_open_four'), (2, 'on_full_finish_game')], default=1)),
                ('ace_allowed', models.BooleanField(default=True)),
                ('on_eggs', models.IntegerField(choices=[(1, 'on_eggs_open_four'), (2, 'on_eggs_open_double')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
